version: "3"
services:
  # MongoDB
  mongo:
    image: mongo
    ports:
      - 27017:27017

  # Backend
  backend:
    image: backend
    build:
      context: backend
      dockerfile: Dockerfile.development
    env_file: ./backend/.env.development
    ports:
      - 3000:3000
      - 35729:35729
    depends_on:
      - mongo
    volumes:
      - ./backend/src:/app/src
      - ./backend/__tests__:/app/__tests__
      # Mount storage volume/folder into container
      # (for Raspberry Pi, point to USB)
      - ./backend/media:/app/media

  # Dashboard
  dashboard:
    image: dashboard
    build:
      context: dashboard
      dockerfile: Dockerfile.development
    ports:
      - 8080:8080
    volumes:
      - ./dashboard/src:/app/src
      - ./dashboard/public:/app/public
    env_file: ./dashboard/.env.development
