version: "3"
services:
  frontend:
    container_name: home-display-frontend
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      APP_BASE_URL: ${APP_BASE_URL}
      STRAPI_URL: ${STRAPI_URL}
      CDN_BASE_URL: ${CDN_BASE_URL}

  backend:
    container_name: home-display-backend
    build:
      context: backend
      dockerfile: Dockerfile.dev
    environment:
      DATABASE_NAME: "${DATABASE_NAME}"
      DATABASE_HOST: "${DATABASE_HOST}"
      DATABASE_PORT: "${DATABASE_PORT}"
      DATABASE_USERNAME: "${DATABASE_USERNAME}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      JWT_SECRET: "${JWT_SECRET}"
      ADMIN_JWT_SECRET: "${ADMIN_JWT_SECRET}"
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 1337:1337
    depends_on:
      - postgres

  postgres:
    container_name: home-display-db
    image: postgres
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    volumes:
      - home-display-db:/var/lib/postgresql/data

volumes:
  home-display-db:
