FROM node:16-alpine

RUN mkdir /app
WORKDIR /app

COPY package*.json ./

RUN apk add --update --no-cache python3 py3-pip make g++ && rm -rf /var/cache/apk/*

RUN npm install

COPY index.html vite.config.js .eslintrc.js .prettierrc .stylelintrc.js ./
COPY ./src /src

EXPOSE 3000

CMD ["npm", "run", "dev"]