FROM node:16-alpine

# make the 'app' folder the current working directory
WORKDIR /app

# copy both 'package.json' and 'package-lock.json' (if available)
COPY package*.json ./

RUN npm install

# copy project files and folders to the current working directory
COPY . .

RUN npm run build --clean

EXPOSE 1337

CMD ["npm", "run", "develop"]