FROM node:lts-alpine

WORKDIR /app

ADD package.json package-lock.json ./

RUN npm install --quiet

ADD .browserslistrc .prettierrc .eslintrc.js babel.config.js vue.config.js ./

CMD [ "npm", "run", "serve" ]